plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - gemfiles/**/*
    - activejob-uniqueness.gemspec

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*
    - lib/generators/active_job/uniqueness/templates/config/initializers/active_job_uniqueness.rb

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/EmptyBlock:
  Exclude:
    - spec/active_job/uniqueness/sidekiq_patch_spec.rb

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - activejob-uniqueness.gemspec
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - spec/active_job/uniqueness/sidekiq_patch_spec.rb

RSpec/IncludeExamples:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/FloatComparison:
  Enabled: false
